### ISSUE TITLE
Logo Design Offering as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [ctrlaltcookie/McGoats#3]
Hello Sir. I'm a Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks for the attention.

**Comment by ctrlaltcookie** [comment]
Sounds good to me, make a pull request with your contribution. Thanks.

**Comment by anharismail** [comment]
Hi @ctrlaltcookie  , I've designed a logos for this project. This logo concept inspired from chatbot and goat. Very welcome if you have any opinions or suggestions about it.

![McGoats Ver  1](https://user-images.githubusercontent.com/37614260/57601060-bb995880-7585-11e9-90fa-cf1da6add5d9.png)

**Comment by ctrlaltcookie** [comment]
Looks fantastic! I'll add it to the readme along with credit to you as the author. Thanks a lot for making it :)

**Comment by anharismail** [comment]
Thanks for your response. If you don't mind, I can help you make pull requests about it.

**Comment by ctrlaltcookie** [comment]
sure go ahead

**Comment by anharismail** [comment]
Hi @ctrlaltcookie , I've made pull request about the logo.

I also provide all editable files here: https://drive.google.com/drive/u/1/folders/1cW3H0Mlu2-GztPQklZbFOLhnzKkwqXWC

very nice can contibute to your open source project
